OCR.MVC.WebApp/Controllers/MastersController.cs
using Microsoft.AspNetCore.Mvc;

namespace OCR.MVC.WebApp.Controllers
{
    public class MastersController : Controller
    {
        public IActionResult Medicines()
        {
            return View();
        }
        public IActionResult Doctors()
        {
            return View();
        }
        public IActionResult Patients()
        {
            return View();
        }

        public IActionResult Suppliers()
        {
            return View();
        }
    }
}

OCR.MVC.WebApp/Controllers/TransactionsController.cs
using Microsoft.AspNetCore.Mvc;

namespace OCR.MVC.WebApp.Controllers
{
    public class TransactionsController : Controller
    {
        public IActionResult Order()
        {
            return View();
        }
        public IActionResult Selling()
        {
            return View();
        }
        public IActionResult Cashier()
        {
            return View();
        }
    }
}

OCR.MVC.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Apotek Nia Farma</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <link href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css" rel="stylesheet" />
    @*<link href="~/css/datatable/jquery.dataTables.min.css" rel="stylesheet" />*@

    <link href="https://cdn.datatables.net/buttons/2.1.0/css/buttons.dataTables.min.css" rel="stylesheet" />
    @*<link href="~/css/datatable/buttons.dataTables.min.css" rel="stylesheet" />*@

    <link href="~/lib/toastr/toastr.min.css" rel="stylesheet" />
    <link href="~/css/sweetalert/sweetalert2.min.css" rel="stylesheet" />
    <link href="~/css/font-awesome/font-awesome.min.css" rel="stylesheet" />
</head>
<style>
    .dropdown:hover > .dropdown-menu {
        display: block;
    }
    .dropdown-menu a:hover {
        color: #00653b !important;
    }
    .bg-apotek {
        background-color: #00653b;
    }
    .bg-apotek-nav {
        background-color: #d4edda;
    }
</style>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark border-bottom box-shadow mb-3 bg-apotek fixed-top">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/nia-logo.png" width="166" height="40" class="d-inline-block align-top" alt="">
                </a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between pl-4">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false">
                                Masters
                            </a>
                            <div class="dropdown-menu bg-apotek" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item text-light" href="@Url.Action("Medicines","Masters")">Obat</a>
                                <a class="dropdown-item text-light" href="@Url.Action("Medicines","Masters")">Jasa</a>
                                <a class="dropdown-item text-light" href="@Url.Action("Medicines","Masters")">Paket</a>
                                <a class="dropdown-item text-light" href="@Url.Action("Type","Masters")">Golongan Produk</a>
                                <a class="dropdown-item text-light" href="@Url.Action("Type","Masters")">Rak</a>
                                <a class="dropdown-item text-light" href="@Url.Action("Patients","Masters")">Merk</a>
                                <a class="dropdown-item text-light" href="@Url.Action("Suppliers","Masters")">Supplier</a>
                                <a class="dropdown-item text-light" href="@Url.Action("Patients","Masters")">Pasien</a>
                                <a class="dropdown-item text-light" href="@Url.Action("Banks","Masters")">Bank</a>
                                <a class="dropdown-item text-light" href="@Url.Action("Type","Masters")">Jenis Racikan</a>
                                <a class="dropdown-item text-light" href="@Url.Action("Doctors","Masters")">Dokter</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false">
                                Transactions
                            </a>
                            <div class="dropdown-menu bg-apotek" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item text-light" href="@Url.Action("Cashier","Transactions")">Mesin Kasir</a>
                                <a class="dropdown-item text-light" href="@Url.Action("Cashier","Transactions")">Reprint Nota Penjualan</a>
                                <a class="dropdown-item text-light" href="@Url.Action("Cashier","Transactions")">Buka Cash Drawer</a>
                                <a class="dropdown-item text-light" href="@Url.Action("Selling","Transactions")">Penjualan</a>
                                <a class="dropdown-item text-light" href="@Url.Action("Selling","Transactions")">Retur Penjualan</a>
                                <a class="dropdown-item text-light" href="@Url.Action("Selling","Transactions")">Order Penjualan</a>
                                <a class="dropdown-item text-light" href="@Url.Action("Selling","Transactions")">Pelunasan Piutang</a>
                                <a class="dropdown-item text-light" href="@Url.Action("Order","Transactions")">Pembelian</a>
                                <a class="dropdown-item text-light" href="@Url.Action("Order","Transactions")">Retur Pembelian</a>
                                <a class="dropdown-item text-light" href="@Url.Action("Order","Transactions")">Order Pembelian</a>
                                <a class="dropdown-item text-light" href="@Url.Action("Order","Transactions")">Pelunasan Hutang</a>
                                <a class="dropdown-item text-light" href="@Url.Action("Opname","Transactions")">Opname/Koreksi Stok</a>
                                <a class="dropdown-item text-light" href="@Url.Action("Opname","Transactions")">Mutasi Stok</a>
                                <a class="dropdown-item text-light" href="@Url.Action("Opname","Transactions")">Assembly Stok</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false">
                                Reports
                            </a>
                            <div class="dropdown-menu bg-apotek" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item text-light" href="#">Report Obat</a>
                                <a class="dropdown-item text-light" href="#">Report Pasien</a>
                                <a class="dropdown-item text-light" href="#">Report Dokter</a>
                                <a class="dropdown-item text-light" href="#">Report Supplier</a>
                            </div>
                        </li>
                    </ul>
                    <form class="form-inline my-2 my-lg-0">
                        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3" style="padding-top:80px">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container-fluid">
            &copy; 2021
        </div>
    </footer>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery/datatable/jquery.dataTables.min.js"></script>
    <script src="~/lib/jquery/datatable/dataTables.buttons.min.js"></script>
    <script src="~/lib/jquery/datatable/jszip.min.js"></script>
    <script src="~/lib/jquery/datatable/pdfmake.min.js"></script>
    <script src="~/lib/jquery/datatable/vfs_fonts.js"></script>
    <script src="~/lib/jquery/datatable/buttons.html5.min.js"></script>
    <script src="~/lib/jquery/datatable/buttons.print.min.js"></script>
    <script src="~/lib/moment/moment.js"></script>
    <script src="~/lib/toastr/toastr.min.js"></script>
    <script src="~/lib/sweetalert/sweetalert.min.js"></script>
    <script src="~/lib/sweetalert/sweetalert2@10.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
<script>
    $(document).ready(function () {
        $('#example').DataTable({
            'scrollX': true,
            //scrollCollapse: true,
            dom: 'Bfrtip',
            buttons: [
                //'copy','pdf',
                'csv', 'excel', 'print'
            ]
        });
    });
</script>